mutation{
  bookClass(userId:"5fcca8616a79922708718468",classId:"5fcfc409e37f731e3c05dc21"){
  id
  name	
  role
  phone
  balance
  otp
  onlineClasses
  referralCode
  referedFrom
  referedUsers
  }
}