mutation bookProduct($userId: String!, $productId: String!) {
  bookProduct(userId: $userId, productId: $productId) {
    id
    name
    role
    phone
    currentBalance
    otp
    products
    referralCode
    referedFrom
    referedUsers
  }
}
