query user($id: String!) {
  user(id: $id) {
    id
    firstName
    lastName
    role
    phone
    currentBalance
    otp
    walletId
    children
    parent
    products
    referralCode
    referedFrom
    referedUsers
  }
}
