mutation addChildToParent($parentId: String!, $phone: String!, $otp: String!) {
  addChildToParent(parentId: $parentId, phone: $phone, otp: $otp) {
    id
    name
    role
    phone
    otp
    children
    referralCode
    createdAt
    updatedAt
  }
}
