query getChildOfParent($parentId: String!) {
  getChildOfParent(parentId: $parentId) {
    id
    firstName
    lastName
    role
    phone
    currentBalance
    otp
    walletId
    children
    parent
    products
    referralCode
    referedFrom
    referedUsers
  }
}
