mutation requestToChild($parentId: String!, $phone: String!) {
  requestToChild(parentId: $parentId, phone: $phone) {
    id
    name
    role
    phone
    otp
    children
    referralCode
    createdAt
    updatedAt
  }
}
