mutation{
  saveOnlineClass(
    courseName:"reactt",
    scheduleDateTime:"2020-12-14T06:03:10.597C",
    pricePerHour:70,
  	postedBy:"5fcca8fd6a7992270871846d"
  ){
    id
    courseName
    scheduleDateTime
    pricePerHour
    users
    postedBy
  }
}
