
//UPDATE CLASS
mutation{
  saveOnlineClass(
    id:"5fccd51f911f7a2708c39781"
    courseName:"react",
    scheduleDateTime:"2020-12-14T06:03:10.597C",
    pricePerHour:70,
    seats:40,
  	postedBy:"5fcca8fd6a7992270871846d"
  ){
    id
    courseName
    scheduleDateTime
    pricePerHour
    users
    postedBy
  }
}